In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_excel("../input/mi-assignment/MI_Assignment1_2_Online Retail.xlsx")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   InvoiceNo    541909 non-null  object        
 1   StockCode    541909 non-null  object        
 2   Description  540455 non-null  object        
 3   Quantity     541909 non-null  int64         
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64       
 6   CustomerID   406829 non-null  float64       
 7   Country      541909 non-null  object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB


In [7]:
from statistics import mean, mode

m_d=mode(df['Description'])
m_d

'WHITE HANGING HEART T-LIGHT HOLDER'

In [8]:
from pandas.core.algorithms import mode
df['Description'].fillna(m_d,inplace=True)
a=[]
for i in df["CustomerID"]:
  if not np.isnan(i):
    a.append(i)
df["CustomerID"].fillna(float(mode(a)),inplace=True)
for i in df.index:
  if df['Quantity'][i]<0:
    df['Quantity'][i]=df['Quantity'][i]*-1

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.


In [9]:
ind=0
for i in range(len(df)):
    if df['InvoiceDate'][i]> pd.Timestamp(2011,9,1):
        ind=i
        break

In [10]:
df[ind+1:]

InvoiceNo StockCode                         Description  Quantity  \
320706    565080     22128          PARTY CONES CANDY ASSORTED        24   
320707    565081     21067  WHITE HANGING HEART T-LIGHT HOLDER         1   
320708    565082     22423            REGENCY CAKESTAND 3 TIER         2   
320709    565082    15060B          FAIRY CAKE DESIGN UMBRELLA         8   
320710    565082     23245          SET OF 3 REGENCY CAKE TINS         4   
...          ...       ...                                 ...       ...   
541904    581587     22613         PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899        CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254       CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255     CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138       BAKING SET 9 PIECE RETROSPOT          3   

               InvoiceDate  UnitPrice  CustomerID         Country  
320706 2011-09-01 08:25:00       1.25     13509.0  United Kingdom  
320707 2011-09-01 09:03:00       0.00     17841.0  United Kingdom  
320708 2011-09-01 09:15:00      12.75     13305.0  United Kingdom  
320709 2011-09-01 09:15:00       3.75     13305.0  United Kingdom  
320710 2011-09-01 09:15:00       4.95     13305.0  United Kingdom  
...                    ...        ...         ...             ...  
541904 2011-12-09 12:50:00       0.85     12680.0          France  
541905 2011-12-09 12:50:00       2.10     12680.0          France  
541906 2011-12-09 12:50:00       4.15     12680.0          France  
541907 2011-12-09 12:50:00       4.15     12680.0          France  
541908 2011-12-09 12:50:00       4.95     12680.0          France  

[221203 rows x 8 columns]

In [11]:
df_t=df[:][:ind]
df_t

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
320700   C565077     23196        VINTAGE LEAF MAGNETIC NOTEPAD         3   
320701   C565077     22189              CREAM HEART CARD HOLDER         1   
320702   C565077     23239    SET OF 4 KNICK KNACK TINS POPPIES         1   
320703   C565077     23197    SKETCHBOOK MAGNETIC SHOPPING LIST        12   
320704   C565078         D                             Discount         1   

               InvoiceDate  UnitPrice  CustomerID         Country  
0      2010-12-01 08:26:00       2.55     17850.0  United Kingdom  
1      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
2      2010-12-01 08:26:00       2.75     17850.0  United Kingdom  
3      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
4      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
...                    ...        ...         ...             ...  
320700 2011-08-31 17:31:00       1.45     17451.0  United Kingdom  
320701 2011-08-31 17:31:00       3.95     17451.0  United Kingdom  
320702 2011-08-31 17:31:00       4.15     17451.0  United Kingdom  
320703 2011-08-31 17:31:00       1.45     17451.0  United Kingdom  
320704 2011-08-31 17:45:00      57.60     16422.0  United Kingdom  

[320705 rows x 8 columns]

In [12]:
after=[]
for i in df['CustomerID'][ind+1:]:
    after.append(i)
len(after)    
after=np.array(after)
after=np.unique(after)

In [13]:
lis=[0]*len(df_t)
for i in range(len(df_t)):
    if df_t['CustomerID'][i] in after:
        lis[i]="Not Churn"
    else:
        lis[i]="Churn"


In [14]:
df_t['Target']=lis

In [15]:
df_t['Target']

0             Churn
1             Churn
2             Churn
3             Churn
4             Churn
            ...    
320700    Not Churn
320701    Not Churn
320702    Not Churn
320703    Not Churn
320704    Not Churn
Name: Target, Length: 320705, dtype: object

In [16]:
df_t

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
320700   C565077     23196        VINTAGE LEAF MAGNETIC NOTEPAD         3   
320701   C565077     22189              CREAM HEART CARD HOLDER         1   
320702   C565077     23239    SET OF 4 KNICK KNACK TINS POPPIES         1   
320703   C565077     23197    SKETCHBOOK MAGNETIC SHOPPING LIST        12   
320704   C565078         D                             Discount         1   

               InvoiceDate  UnitPrice  CustomerID         Country     Target  
0      2010-12-01 08:26:00       2.55     17850.0  United Kingdom      Churn  
1      2010-12-01 08:26:00       3.39     17850.0  United Kingdom      Churn  
2      2010-12-01 08:26:00       2.75     17850.0  United Kingdom      Churn  
3      2010-12-01 08:26:00       3.39     17850.0  United Kingdom      Churn  
4      2010-12-01 08:26:00       3.39     17850.0  United Kingdom      Churn  
...                    ...        ...         ...             ...        ...  
320700 2011-08-31 17:31:00       1.45     17451.0  United Kingdom  Not Churn  
320701 2011-08-31 17:31:00       3.95     17451.0  United Kingdom  Not Churn  
320702 2011-08-31 17:31:00       4.15     17451.0  United Kingdom  Not Churn  
320703 2011-08-31 17:31:00       1.45     17451.0  United Kingdom  Not Churn  
320704 2011-08-31 17:45:00      57.60     16422.0  United Kingdom  Not Churn  

[320705 rows x 9 columns]

In [17]:
del df_t['InvoiceDate']
del df_t['Description']
del df_t['Country']
del df_t['StockCode']
del df_t['InvoiceNo']
df_t=df_t.dropna()

In [18]:
x = df_t.iloc[:,0:-1].values
y = df_t.iloc[:,-1].values


In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=42)

In [20]:
from sklearn.svm import SVC
model =SVC()
model.fit(X_train,y_train)

SVC()

In [21]:
y_pred = model.predict(X_test)
y_pred

array(['Not Churn', 'Not Churn', 'Not Churn', ..., 'Not Churn',
       'Not Churn', 'Not Churn'], dtype=object)

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_pred,y_test)


array([[    1,     0],
       [11063, 69113]])

In [23]:
a1=accuracy_score(y_pred,y_test)*100

In [24]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [25]:
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,max_depth = 6, min_samples_leaf = 5)
c=clf_entropy.fit(X_train, y_train)

In [26]:
y_pred1 = c.predict(X_test)
print(y_pred)

['Not Churn' 'Not Churn' 'Not Churn' ... 'Not Churn' 'Not Churn'
 'Not Churn']


In [27]:
confusion_matrix(y_test, y_pred1)

array([[  853, 10211],
       [  294, 68819]])

In [28]:
a2=accuracy_score(y_test,y_pred1)*100
a2

86.89773875300897

In [29]:
classification_report(y_test, y_pred1)

'              precision    recall  f1-score   support\n\n       Churn       0.74      0.08      0.14     11064\n   Not Churn       0.87      1.00      0.93     69113\n\n    accuracy                           0.87     80177\n   macro avg       0.81      0.54      0.53     80177\nweighted avg       0.85      0.87      0.82     80177\n'

In [30]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(15,), random_state=1)
clf.fit(X_train, y_train)
p2=clf.predict(X_test)

/opt/conda/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [31]:
confusion_matrix(y_test, p2)

array([[    0, 11064],
       [    0, 69113]])

In [32]:
a3=accuracy_score(y_test,p2)*100

In [33]:
classification_report(y_test, p2)

/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


'              precision    recall  f1-score   support\n\n       Churn       0.00      0.00      0.00     11064\n   Not Churn       0.86      1.00      0.93     69113\n\n    accuracy                           0.86     80177\n   macro avg       0.43      0.50      0.46     80177\nweighted avg       0.74      0.86      0.80     80177\n'

In [34]:
print(a1,a2,a3)

86.2017785649251 86.89773875300897 86.20053132444467
