**Name** - Srinandan A

**SRN** - PES1UG20CS596

**Section** - J

## Problem 1

In [1]:
# Importing Libraries
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
# encoding the probabilities as a numpy array
trans_array = np.array([
    [0.002, 0.666, 0.31, 0, 0.022],
    [0.466, 0.102, 0.222, 0, 0.21],
    [0.022, 0.11, 0.502, 0, 0.366],
    [0, 0, 0, 1, 0],
    [0.11, 0.122, 0.066, 0, 0.702]
])
# ensures that the probabilities sum to 1
assert(trans_array[0].sum() == 1.0)
assert(trans_array[1].sum() == 1.0)
assert(trans_array[2].sum() == 1.0)
assert(trans_array[3].sum() == 1.0)
assert(trans_array[4].sum() == 1.0)



# encoding the initial probability of as a numpy array
state = np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])
assert(state[0].sum() == 1.0)

**Q1. What technique can be used to model the probability of people going to the correct unit to report thier crime after N days? (0 points)**

The probability of people going to the correct unit to report their crime is modeled by obtaining general formula from the eigen value of transition matrix. 

In [3]:
matC = np.dot(state, trans_array)
print(matC)

[[0.1947 0.2577 0.2353 0.15   0.1623]]


**Q2. Is the chain irreducible? Justify (0.5 point)**

A markov chain is said to be irreducible when each state can travel to any other state.
The given markov chain is not irreducible since state 4 is a trap state (starting from state 4, we cannot travel to any other state )

**Q3. What will be the intital probability of a person going to a particular unit after 1 day, 2 days, 10 days, 1000 days and 1001 days. (1 point)**

In [4]:
matC = state

count = 1
while count < 1002:
    matC = np.dot(matC, trans_array)
    if count == 1:
        print(f"Day {count} - {matC}")
    elif count == 2:
        print(f"Day {count} - {matC}")
    elif count == 1000:
        print(f"Day {count} - {matC}")
    elif count == 1001:
        print(f"Day {count} - {matC}")
    count += 1

Day 1 - [[0.1947 0.2577 0.2353 0.15   0.1623]]
Day 2 - [[0.1435072 0.2016392 0.2463988 0.15      0.2584548]]
Day 1000 - [[0.1214373  0.16411091 0.19739717 0.15       0.36705462]]
Day 1001 - [[0.1214373  0.16411091 0.19739717 0.15       0.36705462]]


**Q4. What can you say about the markov chain from state of intital probability of a person going to a particular unit after 1000 and 1001 days? (0.5 points)**

The values of day 1000 and day 10001 are equal. Hence, we can say that the markov chain has attained a steady state.

## Problem 2

**Q1. Is the chain irreducible? Justify (0.5 point)**

A markov chain is said to be irreducible when each state can travel to any other state.
The given markov chain is not irreducible since state 3 and state 4 cannot be reached from any other state.

In [5]:
# encoding the probabilities as a numpy array
trans_array = np.array([
    [0.002, 0.666, 0.01, 0.020, 0.302],
    [0.466, 0.102, 0.02, 0.032, 0.38],
    [0.0, 0.0, 1, 0.0, 0.0],
    [0, 0, 0, 1, 0],
    [0.11, 0.122, 0.066, 0.004, 0.698]
])

# ensures that the probabilities sum to 1
assert(trans_array[0].sum() == 1.0)
assert(trans_array[1].sum() == 1.0)
assert(trans_array[2].sum() == 1.0)
assert(trans_array[3].sum() == 1.0)
assert(trans_array[4].sum() == 1.0)

# encoding the initial probability of as a numpy array
state = np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])
assert(state[0].sum() == 1.0)

**Q2. What will be the intital probability of a person going to a particular unit after 1 day, 2 days, 10 days, 1000 days and 1001 days. (1 point)**

In [6]:
matC = state

count = 1
while count < 1002:
    matC = np.dot(matC, trans_array)

    if count == 1:
        print(f"Day {count} - {matC}")
    elif count == 2:
        print(f"Day {count} - {matC}")
    elif count == 1000:
        print(f"Day {count} - {matC}")
    elif count == 1001:
        print(f"Day {count} - {matC}")
    count += 1

Day 1 - [[0.1925 0.2467 0.1143 0.169  0.2775]]
Day 2 - [[0.1458722 0.1872234 0.139474  0.1818544 0.345576 ]]
Day 1000 - [[8.97378472e-28 1.13004326e-27 6.60595331e-01 3.39404669e-01
  2.87688168e-27]]
Day 1001 - [[8.44851901e-28 1.06389804e-27 6.60595331e-01 3.39404669e-01
  2.70848815e-27]]


**Q3. What can you say about the markov chain from state of intital probability of a person going to a particular unit after 1000 and 1001 days? (0.5 points)**

The values of day 1000 and day 1001 are not equal. Hence, we can say that this markov chain has not attained a steady state yet.

**4. Summer Edgecombe is Confidential Informant (CI) to the Officer Kimbal Cho and comes in every day to the police station. If on the first day she goes to the Major crimes Unit what will be the probability that she gives a feedback? (2 points)**

```python
# np.delete()
# https://note.nkmk.me/en/python-numpy-delete/#:~:text=Using%20the%20NumPy%20function%20np,from%20the%20NumPy%20array%20ndarray%20.&text=Specify%20the%20axis%20(dimension)%20and,a%20slice%20or%20a%20list.

print(a)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

print(np.delete(a, 1, 0))
# [[ 0  1  2  3]
#  [ 8  9 10 11]]

print(np.delete(a, 1, 1))
# [[ 0  2  3]
#  [ 4  6  7]
#  [ 8 10 11]]

# Deleting multiple rows or columns
print(np.delete(a, [0, 3], 1))
# [[ 1  2]
#  [ 5  6]
#  [ 9 10]]

# Deleting rows and columns
print(np.delete(np.delete(a, 1, 0), 1, 1))
# [[ 0  2  3]
#  [ 8 10 11]]

# matrix multiplication or cross pdt C = A*B
matrix_C = matrix_A @ matrix_B # matrix_C = np.matmul(matrix_A, matrix_B)

In [7]:
state @ trans_array

array([[0.1925, 0.2467, 0.1143, 0.169 , 0.2775]])

## Problem 3

In [8]:
# encoding the probabilities as a numpy array
# With Santiago
trans_array_with_amy = np.array([
    [0.002, 0.232, 0.31, 0.434, 0.022],
    [0.426, 0.102, 0.222, 0.04, 0.21],
    [0.03, 0.11, 0.20, 0.294, 0.366],
    [0.003, 0.176, 0.321, 0.3, 0.2],
    [0.11, 0.422, 0.166, 0.1, 0.202]
])

# Without Santiago
trans_array_without_amy = np.array([
    [0.11, 0.222, 0.092, 0.374, 0.202],
    [0.03, 0.11, 0.20, 0.294, 0.366],
    [0.002, 0.232, 0.31, 0.434, 0.022],
    [0.466, 0.102, 0.02, 0.032, 0.38],
    [0.003, 0.176, 0.321, 0.3, 0.2]
])

# ensures that the probabilities sum to 1
assert(trans_array_with_amy[0].sum() == 1.0)
assert(trans_array_with_amy[1].sum() == 1.0)
assert(trans_array_with_amy[2].sum() == 1.0)
assert(trans_array_with_amy[3].sum() == 1.0)
assert(trans_array_with_amy[4].sum() == 1.0)

assert(trans_array_without_amy[0].sum() == 1.0)
assert(trans_array_without_amy[1].sum() == 1.0)
assert(trans_array_without_amy[2].sum() == 1.0)
assert(trans_array_without_amy[3].sum() == 1.0)
assert(trans_array_without_amy[4].sum() == 1.0)

# encoding the initial probability of as a numpy array
state = np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])
assert(state[0].sum() == 1.0)


**Q1. How can you find out the effect that Santiago has on the probability of feedback? (1 point)**

First order markov chains can be used to find out the effect that Santiago has on the probability of feedback.

In [9]:
print(f" With Amy - {state @ trans_array_with_amy}")
print(f"Without Amy - {state @ trans_array_without_amy}")

 With Amy - [[0.17995 0.1689  0.25825 0.2256  0.1673 ]]
Without Amy - [[0.11525 0.1579  0.15765 0.293   0.2762 ]]


**Q2. What effect does Santiago have one the probability of getting feedback? (1 point)**

We can see that due to Santiago being present, the probability of feedback has decreased.

**Q3. Name the test Captain Holt is performing. (0.5 points)**

Anderson-Goodman test - chi squared test

**Q4. Without the information about these inital probabilities, can you tell if there is any difference in the probability of getting a feedback? Explain. (1.5 points)**

We can check if the transition forms a markov chain by performing chi squared test on the transition matrix and find chi squared value and subsequent p value.
