# PROBLEM 0


In [1]:
# Importing necessary libraries
import pandas as pd
import numpy as np 
import ast
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

# Use pandas read_csv function to load csv as DataFrame
df = pd.read_csv('../input/dataset/twitter_HOTD_DA_WORKSHEET4A.csv')
df

author_id             tweet_id  \
0     1576486223442583554  1577813753902555136   
1      732912167846973441  1577813747846254592   
2      891426095928672257  1577813743794257920   
3               352012951  1577813724366249986   
4     1090278774925611008  1577813708818059264   
...                   ...                  ...   
8056           2916627870  1570663468055040000   
8057           2916627870  1570663455606312961   
8058           2916627870  1570663389684453378   
8059            212524158  1570663558563921922   
8060  1497796183279996929  1570663337658298371   

                                                   text  retweet_count  \
0     rt i would perform my duty if mother had only ...            327   
1      rt viserys look at me!! aemond #houseofthedragon           2164   
2     rt house of the dragon is a show about a king ...            905   
3     man just thinking of when viserys finally croa...              0   
4                          rt jajaja. #houseofthedragon             29   
...                                                 ...            ...   
8056  rt may i go on record that if matt smith looke...            166   
8057  rt good morning to matt smith who is now respo...            125   
8058  rt the entire world paused during this #houseo...           2485   
8059                                    days left #hotd              0   
8060  the #houseofthedragon cast is too small. due t...              0   

      reply_count  like_count  quote_count  \
0               0           0            0   
1               0           0            0   
2               0           0            0   
3               0           0            0   
4               0           0            0   
...           ...         ...          ...   
8056            0           0            0   
8057            0           0            0   
8058            0           0            0   
8059            0           5            0   
8060            1           3            0   

                                                 tokens  \
0            ['perform', 'duty', 'mother', 'betrothed']   
1                         ['viserys', 'look', 'aemond']   
2     ['house', 'dragon', 'king', 'bunch', 'question...   
3     ['man', 'thinking', 'viserys', 'finally', 'cro...   
4                                            ['jajaja']   
...                                                 ...   
8056  ['record', 'matt', 'smith', 'looked', 'like', ...   
8057  ['good', 'morning', 'matt', 'smith', 'responsi...   
8058                      ['entire', 'world', 'paused']   
8059                                   ['days', 'left']   
8060  ['cast', 'small', 'producers', 'afford', 'kill...   

                                               hashtags  
0     ['houseofthedragon', 'aemondtargaryen', 'helae...  
1                                  ['houseofthedragon']  
2                                                    []  
3                                  ['houseofthedragon']  
4                                  ['houseofthedragon']  
...                                                 ...  
8056                                                 []  
8057                                                 []  
8058                               ['houseofthedragon']  
8059                                           ['hotd']  
8060             ['houseofthedragon', 'gameofthrones.']  

[8061 rows x 9 columns]

# PROBLEM 1
Tokenize the string representations provided in the **tokens** column of the DataFrame using TF-IDF from sklearn. Then print out the TF-IDF of the first row of the DataFrame.

In [2]:
# Convert string representation of a list into a list of strings
text = []
for r in df['tokens']:
    res = ast.literal_eval(r)
    if(' '.join(res).lower() == ''):
        print(r)
    text.append(' '.join(res).lower())
# Print the end result
text

['perform duty mother betrothed',
 'viserys look aemond',
 'house dragon king bunch questionable decisions based idea dead',
 'man thinking viserys finally croaks fucking races gon na fucking hate damn cliffhanger making wait year war start lol',
 'jajaja',
 'funny 😂 😂',
 'way lucerys threw blade sending 😭',
 'house dragon alright kinda dog',
 'showmax watch house dragon nigeria',
 'poor guy 😅 😂',
 'trying catchup house dragon rhaenyra better written galadriel rop.',
 'daemon targaryen criston cole owner 🤫',
 'daemyra',
 'love scene fucking',
 'house dragon bollywood',
 'opening targaryen family tree bloodline represented king viserys valyria model diorama ama',
 'baela rhaena 🥺 younger older',
 'green like alicent',
 'watching ep',
 'scenes photos episode',
 'viserys raven reaches king landing informs rhaenyra daemon got married',
 'year ago today got official teaser',
 'aemon holding life 🤣 🤣 happy biggest dragon',
 'imagine scene song \x01f90c 💀',
 'living sons remained strength con

In [3]:
tf_idf = TfidfVectorizer()
text_tf = tf_idf.fit_transform(text)
text_tf = tf_idf.transform(text)
print("n_samples: %d, n_features: %d" % text_tf.shape)
text_tf=text_tf.toarray()
print(text_tf)

n_samples: 8061, n_features: 10950
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# PROBLEM 2
Find the top-5 most similar tweets to the tweet with index `7558` using cosine similarity between the TF-IDF vectors.

In [4]:
result=cosine_similarity(text_tf, dense_output=True)
result=np.argsort(result)

In [5]:
for i in range(5):
    index=result[7558][i]
    print(text[index])
    print(df.iloc[index])

perform duty mother betrothed
author_id                                      1576486223442583554
tweet_id                                       1577813753902555136
text             rt i would perform my duty if mother had only ...
retweet_count                                                  327
reply_count                                                      0
like_count                                                       0
quote_count                                                      0
tokens                  ['perform', 'duty', 'mother', 'betrothed']
hashtags         ['houseofthedragon', 'aemondtargaryen', 'helae...
Name: 0, dtype: object
weird means corlys inherit house gives son away fae4#houseofthedragonhbo
author_id                                                 79612538
tweet_id                                       1571987975638257665
text             this is weird. that means corlys has no one to...
retweet_count                                                    0
re

In [6]:
print(text[7558])
print(df.iloc[7558][2])

viserys wanna build lego set mind business let man live peace
rt viserys just wanna build his lego set and mind his business . let that man live in peace #houseofthedragon


# PROBLEM 3
A great disadvantage in using TF-IDF is that it can not capture semantics. If you had classify tweets into positive/negative, what technique would you use to map words to vectors? In short words, provide the sequence of solution steps to solve this task. Note: Assume sentiment labels have been provided. 

If i had to classify tweets into positive/negative, the technique I would use to map words to vectors is Word Embeddings/Word Vectorization using Word2Vec.

Word2Vec consists of models for generating word embedding. These models are shallow two-layer neural networks having one input layer, one hidden layer, and one output layer. Word2Vec utilizes two architectures :

1. CBOW (Continuous Bag of Words)
2. Skip Gram 

Solution steps:
1. Replacing escape characters with space.
2. Tokenize each sentence into words by iterating through each sentence in the file.
3. Create CBOW or SG model using gensim.models.Word2Vec function.
4. Print the results.